export const ADD_ELEMENT = 'ADD_ELEMENT';
export const DELETE_ELEMENT = 'DELETE_ELEMENT';
export const DISPLAY_ELEMENT_SETTINGS = 'DISPLAY_ELEMENT_SETTINGS';
export const DISPLAY_ELEMENT_IN_FULL_SCREEN = 'DISPLAY_ELEMENT_IN_FULL_SCREEN';
export const RESET_ELEMENT_COUNT = 'RESET_ELEMENT_COUNT';
export const RENAME_ELEMENT = 'RENAME_ELEMENT';
export const CHANGE_ELEMENT_INCREMENT_BY = 'CHANGE_ELEMENT_INCREMENT_BY';
export const CHANGE_ELEMENT_COUNT = 'CHANGE_ELEMENT_COUNT';